# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Cloud-DevOps Ninja
description: >- # this means to ignore newlines until "baseurl:"
  Sharing my adventures as a Cloud DevOps ninja
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
show_downloads: false
logo: 'assets/images/logo-white.png'
favicon: 'assets/images/favicon.ico'
paginate: 10
#google_analytics:
twitter_username: cdo_ninja
github_username:  cloud-devops-ninja
email: info[at]cloud-devops[dot]ninja
author: [cdo-ninja]

# Build settings
#theme: minima
theme: jekyll-theme-hacker
remote-theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme #enable github pages themes
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Authors
authors:
  esther:
    reviewer: false
    name: Esther
    display_name: Esther Barthel
    company: cognition IT
    title: 'Solutions Architect'
    picture: 'assets/images/authors/esther.png'
    web: https://www.cognitionit.com
    twitter: https://twitter.com/virtuEs_IT
    linkedin: https://www.linkedin.com/in/ebarthel
    github: https://github.com/cognitionit
    page: esther-barthel
    description: "Esther is currently working as a Solutions Architect at cognition IT, focused on EUC and DevOps/Everything-as-Code projects."
  cdo-ninja:
    reviewer: false
    name: CDOninja
    display_name: Cloud-DevOps ninja
    company: ''
    title: 'Cloud-DevOps ninja'
    picture: 'assets/images/authors/cdo-ninja.gif'
    twitter: https://twitter.com/cdo_ninja
    github: https://github.com/cloud-devops-ninja
    page: cdo-ninja
    description: "The Cloud-DevOps ninja strikes again!"
